imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"
# limitsHugepages2Mi: 100Mi
# limitsHugepages1Gi: 2Gi
timeout: "1200"
# Service
service:
  # Provide any additional service annotations
  annotations: {}
# GCP PDs and EBS volumes are supported only
persistence:
  enabled: false # Set to true to enable persistence
  accessMode: ReadWriteOnce
  size: 5Gi # PVC size
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## Storage class of PV to bind. By default it looks for standard storage class.
  ## If the PV uses a different storage class, specify that here.
  storageClass: ""
  volumeName: ""
# The username and password to be used by the on-cluster database.
# If left empty they will be generated using randAlphaNum
username: ""
password: ""
passportDatabaseName: "drycc_passport"
controllerDatabaseName: "drycc_controller"
