{{ if eq .Values.global.databaseLocation "on-cluster"}}
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  labels:
    app: drycc-database
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  user: {{ if .Values.username | default "" | ne "" }}{{ .Values.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if .Values.password | default "" | ne "" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}
