{{- if eq .Values.global.databaseLocation "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-database
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-database
  template:
    metadata:
      labels:
        app: drycc-database
    spec:
      {{- include "common.affinities.pods.soft" (dict "key" "app" "values" (list "drycc-database")) | indent 6 }}
      serviceAccount: drycc-database
      initContainers:
      - name: drycc-database-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -a
          - $(DRYCC_MINIO_ENDPOINT)
        {{- include "builder.envs" . | indent 8 }}
      containers:
      - name: drycc-database
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/postgres:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
        - containerPort: 5432
        {{- include "builder.limits" . | indent 8 }}
        {{- include "builder.envs" . | indent 8 }}
        lifecycle:
          preStop:
            exec:
              command:
              - init-stack
              - gosu
              - postgres
              - do_backup
        readinessProbe:
          exec:
            command:
            - init-stack
            - is_running
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: database-creds
          mountPath: /var/run/secrets/drycc/database/creds
        - name: minio-creds
          mountPath: /var/run/secrets/drycc/minio/creds
        {{- if .Values.persistence.enabled }}
        - name: database-data
          mountPath: /data
        {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: database-data
        persistentVolumeClaim:
          claimName: drycc-database
      {{- end }}
      - name: database-creds
        secret:
          secretName: database-creds
      - name: minio-creds
        secret:
          secretName: minio-creds
{{- end }}
