{{- if eq .Values.global.databaseLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-database
  labels:
    heritage: drycc
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: drycc-database
{{- end }}
