{{- if eq .Values.global.databaseLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-database
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: drycc-database
{{- end }}
