{{- if eq .Values.global.database_location "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-database
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-database
  template:
    metadata:
      labels:
        app: drycc-database
    spec:
      serviceAccount: drycc-database
      containers:
        - name: drycc-database
          image: {{.Values.image_registry}}/{{.Values.image_org}}/postgres:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
          ports:
            - containerPort: 5432
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          env:
            - name: DATABASE_STORAGE
              value: "{{.Values.global.storage}}"
            - name: PGCTLTIMEOUT
              value: "{{.Values.timeout}}"
          lifecycle:
            preStop:
              exec:
                command:
                  - gosu
                  - postgres
                  - do_backup
          readinessProbe:
            exec:
              command:
                - is_running
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: database-creds
              mountPath: /var/run/secrets/drycc/database/creds
            - name: objectstore-creds
              mountPath: /var/run/secrets/drycc/objectstore/creds
      volumes:
        - name: database-creds
          secret:
            secretName: database-creds
        - name: objectstore-creds
          secret:
            secretName: objectstorage-keyfile
{{- end }}
