{{- if eq .Values.global.databaseLocation "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-database
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-database
  template:
    metadata:
      labels:
        app: drycc-database
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset.type "key" .Values.podAffinityPreset.key "values" .Values.podAffinityPreset.values ) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset.type "key" .Values.podAntiAffinityPreset.key "values" .Values.podAntiAffinityPreset.values ) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-database
      initContainers:
      - name: drycc-database-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -g
          - $(DRYCC_STORAGE_HEALTH)
        {{- include "database.envs" . | indent 8 }}
      containers:
      - name: drycc-database
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/postgres:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
        - containerPort: 5432
        {{- include "database.limits" . | indent 8 }}
        {{- include "database.envs" . | indent 8 }}
        lifecycle:
          preStop:
            exec:
              command:
              - init-stack
              - gosu
              - postgres
              - do_backup
        readinessProbe:
          exec:
            command:
            - init-stack
            - is_running
          initialDelaySeconds: 30
          timeoutSeconds: 1
      {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: database-data
          mountPath: /data
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: drycc-database
      {{- end }}
{{- end }}
